### ISSUE TITLE
solc is called 1 time for each *.sol file in contracts dir

### ISSUE THREAD

**Issue by perissology** [embark-framework/embark-solc#13]
It looks like solc is being called 1 time per file in the `contracts/` dir. I logged 17 calls to solc and I have 17 files in `contracts/`.

This leads to the same warning being printed multiple times multiple contract files import a single dependency & that dependency issues a warning.

As you can see in the following screenshot, there are duplicate warnings for `EVMScriptRunner.sol` contract.

<img width="1439" alt="screen shot 2018-11-15 at 10 50 30 am" src="https://user-images.githubusercontent.com/30963004/48574643-8ce74180-e8c4-11e8-82f9-9f37db5275b7.png">

It seems like a better approach would be to create a single standard json file containing all contracts to be compiled & then making a single call to `solc`

**Comment by jrainville** [comment]
FYI, starting to work on this issue this iteration.

**Comment by jrainville** [comment]
Now fixed in develop.
