### ISSUE TITLE
race condition when checking solc version

### ISSUE THREAD

**Issue by ewingrj** [embark-framework/embark-solc#18]
There is currently a race condition caused by the solc version check which will cause this plugin to load, but the solcjs compiler to run

**Comment by jrainville** [comment]
Starting to work on this right now

**Comment by jrainville** [comment]
Fixed with both those PRs: 
https://github.com/embark-framework/embark/pull/1259
https://github.com/embark-framework/embark-solc/pull/21

**Comment by jrainville** [comment]
I just published v4.0.0 of the plugin which contains the fix to this issue. 
Don't hesitate if this issue or another one arises.
