### ISSUE TITLE
should throw an error if solc version doesn't match `embark.json` solc version

### ISSUE THREAD

**Issue by perissology** [embark-framework/embark-solc#8]
Current behavior is to just compile the contracts w/o checking cli `solc` version

**Comment by jrainville** [comment]
Looking at it right now

**Comment by jrainville** [comment]
Fixed here: https://github.com/embark-framework/embark-solc/pull/10

**Comment by perissology** [comment]
If the contracts are pinned to say 0.4.18 but I have 0.4.24, this fix won't cover that case correct?

**Comment by jrainville** [comment]
No, the fix is only for the globally available solc vs the version that is in `embark,json`.
The version inside the contract is handled by solc itself
