### ISSUE TITLE
compile error when using node_module imports in contract

### ISSUE THREAD

**Issue by perissology** [embark-framework/embark-solc#9]
I'm getting the following error attempting to compile contract that import from `node_modules`:

`Error: Source "@aragon/os/contracts/apps/AragonApp.sol" not found: File outside of allowed directories.`

**Comment by jrainville** [comment]
Right, I think this was fixed in a previous PR, but only in develop. Right now, only master is published on NPM.
@iurimatias Should we publish this plugin's develop as @next too so that people using Embark4.alpha can have the fix?

**Comment by perissology** [comment]
I just tried the develop branch and got the same error. It looks like not all remappings are picked up recursively for the imports, only for imports in the contract to be compiled.

**Comment by jrainville** [comment]
I just checked and I was wrong. The fix is actually not even merged. That's out bad, the PR has been there for a month. Gonna make sure we merge and publish soon

**Comment by perissology** [comment]
@jrainville Are you referring to #7? I tried that PR out to see if it fixes this problem, however it only recognizes a small subset of the contracts in my repo and skips over the rest when compiling

**Comment by jrainville** [comment]
Yeah, that's the one. It's weird that it doesn't recognize some contracts.
I tried quickly and it did fix the `File outside of allowed directories` error, but maybe there is another issue

**Comment by perissology** [comment]
heres the output of this plugin:

<img width="637" alt="screen shot 2018-11-08 at 2 42 08 pm" src="https://user-images.githubusercontent.com/30963004/48231869-8f95e400-e364-11e8-9b82-a9aa8c2f7973.png">

and w/o this plugin:

<img width="597" alt="screen shot 2018-11-08 at 2 42 22 pm" src="https://user-images.githubusercontent.com/30963004/48231880-96245b80-e364-11e8-8461-d4bdde9e4a73.png">


If you want a more update to date repo to easily reproduce lmk & I'll push a commit

**Comment by jrainville** [comment]
No rush. I won't test today. So if you could push before 8 am EST that would be nice

**Comment by perissology** [comment]
https://github.com/Giveth/liquidpledging/commit/fbb61b4bdeaa6627a5b90cda8408157f1b775f74 will work

**Comment by jrainville** [comment]
Fixed in the following PR: https://github.com/embark-framework/embark-solc/pull/12

**Comment by perissology** [comment]
I tried that PR locally with no luck.

<img width="1276" alt="screen shot 2018-11-14 at 7 06 00 am" src="https://user-images.githubusercontent.com/30963004/48491177-d1e37900-e7db-11e8-8e7a-b5c5b28a5b04.png">

**Comment by jrainville** [comment]
Ok, will try again with your repo. I tested with the embark demo where I imported one of Aragon's contract. Hopefully, I am just missing a part.

**Comment by jrainville** [comment]
Alright, updated the PR. Now your repo works totally (tested only building with `embark build --contracts`)

Reason why it was working for you and not for me is that you have contracts that import other contracts that then import the Argon contracts. Before, the remappings only worked for direct imports, so the first file didn't know how to remap the Aragon contract.

Now, all remappings are resolved from the start.

**Comment by perissology** [comment]
okay, cool that works

**Comment by jrainville** [comment]
Closing as it is fixed in develop per https://github.com/embark-framework/embark-solc/pull/12
